package com.cardill.sports.stattracker.creator.game.businesslogic;

public enum GameState {
    MAIN,
    MAKE_ONE_POINT_REQUESTED,
    MAKE_TWO_POINT_REQUESTED,
    DETERMINE_MAKE_EXTRAS,
    ASSIST_REQUESTED,
    MISS_REQUESTED,
    DETERMINE_MISS_EXTRAS,
    BLOCK_REQUESTED,
    DETERMINE_BLOCK_EXTRAS,
    REBOUND_FROM_BLOCK_REQUESTED,
    REBOUND_REQUESTED,
    TURNOVER_REQUESTED,
    DETERMINE_TURNOVER_EXTRAS,
    STEAL_REQUESTED
}
